[package]
name = "day-3-part-2"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
strum_macros = "0.26.4"
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = "0.3.19"
